#!/usr/bin/python3
import os
import sys

from tigress.main import task

obfuscation_combinations = {'A', 'ADC'}
input_path = os.path.abspath(sys.argv[1])
output_path = os.path.abspath(sys.argv[2])
no_of_variants = int(sys.argv[3])

task(input_path, output_path, obfuscation_combinations, no_of_variants)
